version: '3.3'

services:
  drupal:
    build:
      dockerfile: Dockerfile-drupal
      context: ./
    ports:
      - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres:
    build:
      dockerfile: Dockerfile-postgres
      context: ./
    environment:
      POSTGRES_PASSWORD: smile
    restart: always